services:
  mongo:
    image: mongo:8
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    ports: ['27017:27017']
    volumes: ['mongo_data:/data/db']
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand({ ping: 1 }).ok']
      interval: 5s
      timeout: 3s
      retries: 10
  mongo-init:
    image: mongo:8
    depends_on:
      mongo:
        condition: service_healthy
    restart: 'no'
    command:
      [
        'mongosh',
        '--host',
        'mongo:27017',
        '--eval',
        "try { rs.status() } catch(e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }",
      ]
  redis:
    image: redis:7-alpine
    ports: ['6379:6379']
  api:
    build: .
    env_file: .env
    depends_on: [mongo-init, redis]
    ports: ['3000:3000']
volumes:
  mongo_data:
